INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('VEGAN');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('MEXICAN');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('AMERICAN');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('ITALIAN');

INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('TABLESPOON');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('TEASPOON');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('DASH');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('CUP');
INSERT INTO UNIT_OF_MEASURE (UOM) VALUES ('PINT');